language: julia

os: 
  - osx
  - linux

julia:
  - 1.0
  - nightly

notifications:
  email: true

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ShallowWaterModels")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("ShallowWaterModels")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - travis_wait julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
