language: julia

os: osx

julia:
  - 1.0
  - nightly

osx_image: xcode10

before_install:
  - brew update
  - brew install gcc@8 ffmpeg imagemagick cairo

notifications:
  email: true

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ShallowWaterModels")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("ShallowWaterModels")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
